# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14E1H3zSRGT-PP7dLHfDw55aJjOJSoSBT
"""

import torch
print(torch.cuda.is_available())

# !pip install ultralytics

from google.colab import files
files.upload()

import zipfile

zip_path = "bike number plate.v1i.yolov8.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted!")

import yaml

with open("/content/dataset/data.yaml", "r") as f:
    data = yaml.safe_load(f)

data["train"] = "/content/dataset/train/images"
data["val"] = "/content/dataset/valid/images"
data["test"] = "/content/dataset/test/images"

with open("/content/data.yaml", "w") as f:
    yaml.dump(data, f)

print("YAML fixed")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    device=0,
    name="helmet_model"
)

